nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Controllers/SpecificationAttributeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Catalog;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class SpecificationAttributeController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISpecificationAttributeModelFactory _specificationAttributeModelFactory;
        private readonly ISpecificationAttributeService _specificationAttributeService;

        #endregion Fields

        #region Ctor

        public SpecificationAttributeController(ICustomerActivityService customerActivityService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISpecificationAttributeModelFactory specificationAttributeModelFactory,
            ISpecificationAttributeService specificationAttributeService)
        {
            _customerActivityService = customerActivityService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _specificationAttributeModelFactory = specificationAttributeModelFactory;
            _specificationAttributeService = specificationAttributeService;
        }

        #endregion

        #region Utilities

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateAttributeLocalesAsync(SpecificationAttribute specificationAttribute, SpecificationAttributeModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(specificationAttribute,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateAttributeGroupLocalesAsync(SpecificationAttributeGroup specificationAttributeGroup, SpecificationAttributeGroupModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(specificationAttributeGroup,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateOptionLocalesAsync(SpecificationAttributeOption specificationAttributeOption, SpecificationAttributeOptionModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(specificationAttributeOption,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        #endregion

        #region Specification attributes

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> List()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAttributes))
                return AccessDeniedView();

            var model = await _specificationAttributeModelFactory.PrepareSpecificationAttributeGroupSearchModelAsync(new SpecificationAttributeGroupSearchModel());

            return View(model);
        }

        [HttpPost]
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> SpecificationAttributeGroupList(SpecificationAttributeGroupSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAttributes))
                return await AccessDeniedDataTablesJson();

            var model = await _specificationAttributeModelFactory.PrepareSpecificationAttributeGroupListModelAsync(searchModel);

            return Json(model);
        }

        [HttpPost]
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> SpecificationAttributeList(SpecificationAttributeSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAttributes))
                return await AccessDeniedDataTablesJson();

            SpecificationAttributeGroup group = null;

            if (searchModel.SpecificationAttributeGroupId > 0)
            {
                group = await _specificationAttributeService.GetSpecificationAttributeGroupByIdAsync(searchModel.SpecificationAttributeGroupId)
                    ?? throw new ArgumentException("No specification attribute group found with the specified id");
            }

            var model = await _specificationAttributeModelFactory.PrepareSpecificationAttributeListModelAsync(searchModel, group);

            return Json(model);
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> CreateSpecificationAttributeGroup()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAttributes))
                return AccessDeniedView();

            var model = await _specificationAttributeModelFactory.PrepareSpecificationAttributeGroupModelAsync(new SpecificationAttributeGroupModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> CreateSpecificationAttributeGroup(SpecificationAttributeGroupModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAttributes))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var specificationAttributeGroup = model.ToEntity<SpecificationAttributeGroup>();
                await _specificationAttributeService.InsertSpecificationAttributeGroupAsync(specificationAttributeGroup);
                await UpdateAttributeGroupLocalesAsync(specificationAttributeGroup, model);

                await _customerActivityService.InsertActivityAsync("AddNewSpecAttributeGroup",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.AddNewSpecAttributeGroup"), specificationAttributeGroup.Name), specificationAttributeGroup);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Added"));

                if (!continueEditing)
                    return RedirectToAction("List");

                return RedirectToAction("EditSpecificationAttributeGroup", new { id = specificationAttributeGroup.Id });
            }

            model = await _specificationAttributeModelFactory.PrepareSpecificationAttributeGroupModelAsync(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> CreateSpecificationAttribute()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAttributes))
                return AccessDeniedView();

            var model = await _specificationAttributeModelFactory.PrepareSpecificationAttributeModelAsync(new SpecificationAttributeModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> CreateSpecificationAttribute(SpecificationAttributeModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAttributes))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var specificationAttribute = model.ToEntity<SpecificationAttribute>();
                await _specificationAttributeService.InsertSpecificationAttributeAsync(specificationAttribute);
                await UpdateAttributeLocalesAsync(specificationAttribute, model);

                await _customerActivityService.InsertActivityAsync("AddNewSpecAttribute",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.AddNewSpecAttribute"), specificationAttribute.Name), specificationAttribute);

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/CreateSpecificationAttribute.cshtml
@model SpecificationAttributeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Specification attributes");
}

<form asp-controller="SpecificationAttribute" asp-action="CreateSpecificationAttribute" method="post" id="specificationattribute-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.SpecificationAttributeDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateSpecificationAttribute", Model)
</form>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/CreateSpecificationAttributeGroup.cshtml
@model SpecificationAttributeGroupModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Specification attributes");
}

<form asp-controller="SpecificationAttribute" asp-action="CreateSpecificationAttributeGroup" method="post" id="specificationattributegroup-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.SpecificationAttributeGroupDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateSpecificationAttributeGroup", Model)
</form>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/EditSpecificationAttribute.cshtml
@model SpecificationAttributeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.EditAttributeDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Specification attributes");
}

<form asp-controller="SpecificationAttribute" asp-action="EditSpecificationAttribute" method="post" id="specificationattribute-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.EditAttributeDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="specificationattribute-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.SpecificationAttributeDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateSpecificationAttribute", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="specificationattribute-delete" asp-action="DeleteSpecificationAttribute" />

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/EditSpecificationAttributeGroup.cshtml
@model SpecificationAttributeGroupModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.EditAttributeGroupDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Specification attributes");
}

<form asp-controller="SpecificationAttribute" asp-action="EditSpecificationAttributeGroup" method="post" id="specificationattributegroup-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.EditAttributeGroupDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="specificationattributegroup-delete" class="btn bg-red">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.SpecificationAttributeGroupDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateSpecificationAttributeGroup", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="specificationattributegroup-delete" asp-action="DeleteSpecificationAttributeGroup" />

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/List.cshtml
@model SpecificationAttributeGroupSearchModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.SpecificationAttributes").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Specification attributes");
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Admin.Catalog.Attributes.SpecificationAttributes")
    </h1>
    <div class="float-right">
        <a asp-action="CreateSpecificationAttributeGroup" class="btn btn-primary">
            <i class="fas fa-plus-square"></i>
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Buttons.AddNew")
        </a>
        <a asp-action="CreateSpecificationAttribute" class="btn btn-primary">
            <i class="fas fa-plus-square"></i>
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Buttons.AddNew")
        </a>
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.SpecificationAttributeListButtons })
        <button type="button" id="delete-selected-specification-attributes" class="btn btn-danger">
            <i class="far fa-trash-alt"></i>
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Buttons.DeleteSelected")
        </button>
        <nop-action-confirmation asp-button-id="delete-selected-specification-attributes" />
    </div>
</div>

<section class="content">
    <div class="container-fluid">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <p>
                    @T("Admin.Catalog.Attributes.SpecificationAttributes.Description")
                    <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.SpecificationAttributes", Docs.SpecificationAttributes + Utm.OnAdmin)" asp-add-wrapper="false"/>
                </p>
                @await Html.PartialAsync("Table", new DataTablesModel
                {
                    Name = "specificationattributegroups-grid",
                    UrlRead = new DataUrl("SpecificationAttributeGroupList", "SpecificationAttribute", null),
                    PrimaryKeyColumn = nameof(SpecificationAttributeGroupModel.Id),
                    Length = Model.PageSize,
                    LengthMenu = Model.AvailablePageSizes,
                    ColumnCollection = new List<ColumnProperty>
                    {
                        new ColumnProperty(null)
                        {
                            Render = new RenderChildCaret(),
                            Width = "5",
                            Searchable = false,
                            ClassName =  NopColumnClassDefaults.ChildControl
                        },
                        new ColumnProperty(nameof(SpecificationAttributeGroupModel.Name))
                        {
                            Title = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Fields.Name").Text,
                            Render = new RenderCustom("renderColumnNameSpecificationAttributeGroup")
                        },
                        new ColumnProperty(nameof(SpecificationAttributeGroupModel.DisplayOrder))
                        {
                            Title = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Fields.DisplayOrder").Text,
                            Width = "100",
                            ClassName =  NopColumnClassDefaults.CenterAll
                        }
                    },
                    ChildTable = new DataTablesModel
                    {
                        Name = "specificationattributes-grid",
                        UrlRead = new DataUrl("SpecificationAttributeList", "SpecificationAttribute", null),
                        IsChildTable = true,
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        Filters = new List<FilterParameter>
                        {
                            new FilterParameter(nameof(SpecificationAttributeModel.SpecificationAttributeGroupId), nameof(SpecificationAttributeGroupModel.Id), true)
                        },
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(nameof(SpecificationAttributeModel.Id))
                            {
                                IsMasterCheckBox = true,
                                Render = new RenderCheckBox("checkbox_specificationattributes"),
                                ClassName =  NopColumnClassDefaults.CenterAll,
                                Width = "50"
                            },
                            new ColumnProperty(nameof(SpecificationAttributeModel.Name))
                            {
                                Title = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.Name").Text,
                                    Width = "300"
                            },
                            new ColumnProperty(nameof(SpecificationAttributeModel.DisplayOrder))
                            {
                                Title = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.DisplayOrder").Text,
                                Width = "150",
                                ClassName =  NopColumnClassDefaults.CenterAll
                            },
                            new ColumnProperty(nameof(SpecificationAttributeModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "50",
                                ClassName = NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("EditSpecificationAttribute"))
                            }
                        }
                    }
                })

                <script>
                function renderColumnNameSpecificationAttributeGroup(name, type, row, meta) {
                    return row.Id ? '<a href="@Url.Action("EditSpecificationAttributeGroup", "SpecificationAttribute")/' + row.Id +'">' + name + '</a>' : name;
                }

                $(document).ready(function () {
                    $('#delete-selected-specification-attributes-action-confirmation-submit-button').bind('click', function () {
                        var postData = {
                            selectedIds: selectedIds
                        };
                        addAntiForgeryToken(postData);
                        $.ajax({
                            cache: false,
                            type: "POST",
                            url: "@(Url.Action("DeleteSelectedSpecificationAttributes", "SpecificationAttribute"))",
                            data: postData,
                            error: function (jqXHR, textStatus, errorThrown) {
                                $('#delete-selected-specification-attributes-alert-info').text(errorThrown);
                                $('#delete-selected-specification-attributes-alert').click();
                            },
                            complete: function (jqXHR, textStatus) {
                                updateTable('#specificationattributegroups-grid');
                            }
                        });
                        $('#delete-selected-specification-attributes-action-confirmation').modal('toggle');
                        return false;
                    });
                });
                </script>
                <nop-alert asp-alert-id="delete-selected-specification-attributes-alert" />
            </div>
        </div>
    </div>
</div>
</section>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/OptionCreatePopup.cshtml
@model SpecificationAttributeOptionModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.AddNew").Text;
}

<form asp-controller="SpecificationAttribute" asp-action="OptionCreatePopup"
      asp-route-specificationAttributeId="@Context.Request.Query["specificationAttributeId"]" 
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.AddNew")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.SpecificationAttributeOptionDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateOption", Model)
</form>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/OptionEditPopup.cshtml
@model SpecificationAttributeOptionModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.EditOptionDetails").Text;
}
<form asp-controller="SpecificationAttribute" asp-action="OptionEditPopup" 
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.EditOptionDetails")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.SpecificationAttributeOptionDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateOption", Model)
</form>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/_CreateOrUpdateSpecificationAttribute.Info.cshtml
@model SpecificationAttributeModel

<div class="card-body">
    @(await Html.LocalizedEditorAsync<SpecificationAttributeModel, SpecificationAttributeLocalizedModel>("specificationattribute-localized",
    @<div>
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="@Model.Locales[item].Name" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="@Model.Locales[item].Name" />
                <span asp-validation-for="@Model.Locales[item].Name"></span>
            </div>
        </div>
        <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
    </div>
,
    @<div>
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="Name" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="Name" asp-required="true" />
                <span asp-validation-for="Name"></span>
            </div>
        </div>
    </div>))

    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="SpecificationAttributeGroupId" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="SpecificationAttributeGroupId" asp-items="Model.AvailableGroups" />
            <span asp-validation-for="SpecificationAttributeGroupId"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="DisplayOrder" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="DisplayOrder" />
            <span asp-validation-for="DisplayOrder"></span>
        </div>
    </div>
</div>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/_CreateOrUpdateSpecificationAttribute.UsedByProducts.cshtml
@model SpecificationAttributeModel

<div class="card-body">
    @await Html.PartialAsync("Table", new DataTablesModel
    {
        Name = "used-by-products-grid",
        UrlRead = new DataUrl("UsedByProducts", "SpecificationAttribute", new RouteValueDictionary { [nameof(Model.SpecificationAttributeProductSearchModel.SpecificationAttributeId)] = Model.SpecificationAttributeProductSearchModel.SpecificationAttributeId }),
        SearchButtonId = "search-categories",
        Length = Model.SpecificationAttributeProductSearchModel.PageSize,
        LengthMenu = Model.SpecificationAttributeProductSearchModel.AvailablePageSizes,
        ColumnCollection = new List<ColumnProperty>
        {
            new ColumnProperty(nameof(SpecificationAttributeProductModel.ProductName))
            {
                Title = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.UsedByProducts.Product").Text
            },
            new ColumnProperty(nameof(SpecificationAttributeProductModel.Published))
            {
                Title = T("Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.UsedByProducts.Published").Text,
                Width = "100",
                ClassName =  NopColumnClassDefaults.CenterAll,
                Render = new RenderBoolean()
            },
            new ColumnProperty(nameof(SpecificationAttributeProductModel.ProductId))
            {
                Title = T("Admin.Common.View").Text,
                Width = "100",
                ClassName =  NopColumnClassDefaults.Button,
                Render = new RenderButtonView(new DataUrl("~/Admin/Product/Edit/"))
            }
        }
    })
</div>